### ISSUE TITLE
os X version of executible files

### ISSUE THREAD

**Issue by Wenzhe-Ma** [scstein/TrackNTrace#2]
Hello,

I like the package very much. However many of my works are done on a Mac. I wonder if you could add the os X version of executable files to the package?

Thanks
Wenzhe

**Comment by scstein** [comment]
The original source used to compile the mex files is part of the TrackNTrace GitHub repository: https://github.com/scstein/TrackNTrace in the mex/ subfolder. Read the COMPILATION_README.txt file on how to proceed.
 Compilation is only neccessary for the "TNTfitter" and "TNTNearestNeighbor" plugins, the TrackNTrace framework works without them.
 
 I put a MacOS version of the compiled binaries that I created in ~2016 on Google Drive. You can try putting them in the /subfun/ folder and see if it works for you.
-> [TrackNTrace_Mac_Compile.zip](https://drive.google.com/file/d/1_DZsY3etUKALz4WNs1VYTTAqdCAdBn4i/view?usp=sharing)

Unfortunately I don't have access to either Matlab or a Mac, so I can neither recompile nor test these (which is why I wouldn't put them in the repository). Hope that helps!

**Comment by Wenzhe-Ma** [comment]
I tried to compile and failed. I understand you don't have the access to a Mac. Thanks for your help.
